### ISSUE TITLE
Close Button does nothing

### ISSUE THREAD

**Issue by NorlanWaters** [nicolas-t/Chocolat#100]
Hi Nicolas,
first, thank you a lot for this awesome plugin! 

I have one tiny problem with the close button on the overly. It's there, it triggers the pointer but it's doing nothing onclick. What could be the issue?
http://martinschneider-art.de/category/ikonen/ (klick on thumb)

**Comment by nicolas-t** [comment]
Hello !

Congrats on the 100th issue !

In your chocolat javascript file a line is missing : 
http://martinschneider-art.de/wp-content/themes/martin-schneider/js/jquery.chocolat.js?ver=5.1.1
line 491 you have : 

```javascript
$([this.elems.overlay[0], this.elems.close[0]])
    .off('click.chocolat')
    .on('click.chocolat', function() {
        
});
```

instead of : 
https://github.com/nicolas-t/Chocolat/blob/ab742f997720cb0b11a9ffc892d50b3d8de46414/dist/js/jquery.chocolat.js#L464-L468

**Comment by NorlanWaters** [comment]
Worked! Thanks Nicolas! You're the best!
