### ISSUE TITLE
Element selector needs to be an id?

### ISSUE THREAD

**Issue by renestalder** [nicolas-t/Chocolat#34]
I recently started using Chocolat and had some troubles getting started. After looking into the example file on github and the documentation, I saw that it always uses an id as selector for the gallery.

After changing from a class selector to id selector, it worked. So the example on the website is wrong or there is probably a bug which prevents from using it with a class selector e.g. for initializing multiple galleries.

**Comment by nicolas-t** [comment]
Hi,

It should work with class selectors: `.my-class`,
id selectors `#my-ud`,
dom elements, and even jQuery wrapped dom elements.

here is an example working with class selectors (it's demo file included in the /dist/ folder)  :  
https://gist.github.com/nicolas-t/86f03323495a5d5a6f5f6a73a7b685cb

Is your element present in the dom when you call `$('.my-class').Chocolat()` ?
Be sure to replace the `#` by a `.` when refering to a css class instead of a css id.

Don't hesitate to share your code, i'm here to help.

Nicolas,

**Comment by nicolas-t** [comment]
closing, feel free to reopen if needed
