### ISSUE TITLE
Disable Disappearing Viewer

### ISSUE THREAD

**Issue by monopauly** [nicolas-t/Chocolat#38]
Hi,

I was hoping you could help me? 

I am using the API mode to call Chocolat so it is open on page load. This is working fine but the problem I am having is when you click the screen off the image then the viewer disappears, is there anyway to disable this? I notice it works like this on the website demo but I am not knowledgeable enough to understand how it does it. 

Any help would be much appreciated.

**Comment by nicolas-t** [comment]
Hi,
Using the api you can disable the overlay event.

Since you're using the api I guess you're doing a:
`yourInstance.api().open()`
right after you can add;
`yourInstance.api().getElem('overlay').off('click.chocolat')`

in order to disable the click event on the overlay.

If you also want to disable the escape key event you can add 
```
$(document).off('keydown.chocolat').on('keydown.chocolat', function(e) {
    if (yourInstance.api().get('initialized')) {
        if (e.keyCode == 37) {
            yourInstance.api().prev()
        }
        else if (e.keyCode == 39) {
            yourInstance.api().next()
        }
    }
});
```
ps: it's better if you do `yourInstanceApi = yourInstance.api()` and then use `yourInstanceApi` instead of `yourInstance.api()`

tell me if it's ok
Nicolas,

**Comment by monopauly** [comment]
Amazing, thanks so much for your help, it works a treat.

Cheers
Paul
