### ISSUE TITLE
White border just before images load

### ISSUE THREAD

**Issue by afonsogonsalves** [nicolas-t/Chocolat#44]
Hey nicolas, great plugin, thanks :)

I'm having a tiny issue: a white border, the exact dimensions of the image, shows up briefly before the image is rendered. For what it's worth, I've attached a screenshot.

Total noob here, so no idea what this is or how to tackle it... If you could show a way around it, would be awesome, cheers!

![screen shot 2016-07-05 at 23 23 19 1](https://cloud.githubusercontent.com/assets/16281118/16601989/8e663674-4308-11e6-9575-c6d7a5bf93b2.jpg)

**Comment by nicolas-t** [comment]
Hi,
I don't think it's directly related to chocolat.
It looks like a css border of color `#BDBDC6` you can look for this in your code.

Can you upload your code somewhere so I can check it by myself ?
What browser are you using ?
Are you sure the border disappear once the image is loaded ?

**Comment by afonsogonsalves** [comment]
Hey nicolas, thanks for replying so quickly. :)

From what I've checked, this happens Safari, Chrome and Firefox, under OSX 10.11.5. I've tested on Edge and IE on Windows 10 and it doesn't show there.

Anyway, I haven't found any border color applied on the code. Chances are, the website being such a bundled mess of copy-paste code, that some piece is interacting with chocolat somehow.

You can out the website here: www.afonsogonsalves.com/skannwas/
It's still work in progress, a few things are not there yet.

Thanks again

**Comment by nicolas-t** [comment]
I like the way you customized chocolat a lot !
The border you see is in fact the border displayed by the browser for broken images.
That's very strange because chocolat waits for the image to be loaded before displaying it.

![issue44](https://cloud.githubusercontent.com/assets/1765930/16625004/31f072a6-43a3-11e6-92c2-fcd9061ac2cb.jpg)

I'll try to investigate. meanwhile you can reduce the dimensions of your images (as you don't use the zoom feature)

**Comment by nicolas-t** [comment]
So!

I've found a workaround, using the background-image of a `div`, instead of an `img` tag.

Here are the modifications you need :  
-js
https://gist.github.com/nicolas-t/33bbf753c4c556ac5494e403bd91f494/revisions
-css
https://gist.github.com/nicolas-t/bbfa92a537d53e3d1b17d4a434c7e686/revisions

For both the js and css, the revision at the bottom is the original file (chocolat 0.4.14) the revision at the top is the diff you have to reproduce to fix your bug.

I'm not making these changes in master yet. you are kind of a beta tester :)

**Comment by afonsogonsalves** [comment]
Hah! I'm on a shitty net now, but it seems to be working! I'll test it more thoroughly afterwards, will post back if there's any issue remaining.

Thanks man, that was awesome!

Not meaning to push it, but there's something else I've been trying to do, not sure if you can give me a hand: is there a way to have an image cycle (with fade in/out) with another image? Is it possible at all? All the methods I found imply having a div with the images inside, but couldn't apply it within the structure of chocolat.

If it's asking too much, just disregard this. ;)

Thanks again!

**Comment by nicolas-t** [comment]
Hi !

With this diff 
https://gist.github.com/nicolas-t/9bae887e293e917ec98a66916a0805dc/revisions

you can have a fadeOut (300ms) / fadeIn (300ms) effect when changing image.
Not sure if it is what you were looking for (?).

Nicolas,

**Comment by afonsogonsalves** [comment]
Hey!
What I meant is having an image, inside the chocolat overlay/slideshow, that is not static but cycling between two images on a loop, with a fade. Like this: http://jsfiddle.net/5M2PD/4/

Anyway, this would be an optional feature for the website, so if it's not something easy, nevermind! :)
Thanks!

**Comment by nicolas-t** [comment]
To have the loop effect you can use the parameter `loop: true`
If you want it to automaticaly change the image every 3 seconds you can use the API like this:

```javascript
var chocolat = $('#container3').Chocolat({
    loop: true
}).data('chocolat');

chocolat.api().open().done(function(){
    setInterval(function(){ 
        chocolat.api().next()
    }, 3000);
})
```
