### ISSUE TITLE
Control Margin around imageSize:"contain"

### ISSUE THREAD

**Issue by MaxZiebell** [nicolas-t/Chocolat#62]
I want to control the margin around imageSize:'contain' sliders. My slider is also in a container and uses the zoom feature. I attached a screenshot and some CSS I added after a discussion on twitter.
The CSS didn't resolve the issue.

`
      .chocolat-right {
        margin-left : 0px !important;
      }
      .chocolat-left {
        margin-right :0px !important;
      }
      .chocolat-bottom {
        margin-top: 0px !important;
      }
      .chocolat-top {
        margin-bottom: 0px !important;
      }
`
![example](https://cloud.githubusercontent.com/assets/1752114/25542456/013e797a-2c53-11e7-8cf0-ba4021ab2696.jpeg)

**Comment by nicolas-t** [comment]
okay ! this time I get it !

You have to rmove the margin as you did and set
`.chocolat-left, .chocolat-right { width: 0; }` 
`.chocolat-top, .chocolat-bottom { height: 0; line-height: 0; }`

but you won't be able to use the arrows to switch between images.

So _a less bad_ solution would be to modify the js 
in order to make `getOutMarginW` and `getOutMarginH` return 0
https://github.com/nicolas-t/Chocolat/blob/master/dist/js/jquery.chocolat.js#L324L332

```js
        getOutMarginW : function() {
            return 0;
        },

        getOutMarginH : function() {
            return 0;
        },
```

I'll think of adding a custom function as a parameter in order to compute the margins, would be more elegant.

**Comment by MaxZiebell** [comment]
I agree but this solves it for now.
