### ISSUE TITLE
Images without captions show the captions of the last viewed post

### ISSUE THREAD

**Issue by clayton93** [nicolas-t/Chocolat#63]
When you cycle through the images and get to an image without a caption, rather than clearing the .chocolate-description span, the caption from the previous image persists.

**Comment by nicolas-t** [comment]
Hello,

Sorry for the late answer, I've had trouble reproducing the bug.

It happens only if the last image has a title and the first hasn't, while looping.

You can fix this by setting an empty title, like this:  

`<a class="chocolat-image" title="">`
instead of 
`<a class="chocolat-image">`

I'll fix the js in the coming days, i'm quite busy right now.

**Comment by clayton93** [comment]
Ok thanks, I did get to that solution shortly after which worked yep. Thanks!
