### ISSUE TITLE
Reinitialize on window resize?

### ISSUE THREAD

**Issue by rhjp92** [nicolas-t/Chocolat#67]
I am using Chocolat in combination with [Grid-a-licious](http://suprb.com/apps/gridalicious/) to build a responsive image gallery, however I think Grid-a-licious is conflicting with Chocolat because whenever I resize the browser the lightbox will no longer open when I click an image (image opens in a new tab instead). Grid-a-licious rearranges elements in the DOM on window resize so is there a way for Chocolat to "reinitialize" (so to speak) on window resize as well? (sorry my JS skills are very limited.)
Thank you

**Comment by nicolas-t** [comment]
Hello,

Gird-a-licious : 
 - Seems unmaintained (last commit is 2 y o)
 - Conflict with chocolat (and maybe everything else) when resizing
 - Doesn't provide a callback after resizing

So I wouldn't to recommend this library, especially since you have very strong alternatives like masonry : 
https://github.com/desandro/masonry

So imo the way to go is giving a try at Masonry. I can help.

**Comment by rhjp92** [comment]
Thanks for your suggestion. Works perfectly with Masonry 👍
