### ISSUE TITLE
[feature request] swipe?

### ISSUE THREAD

**Issue by stratboy** [nicolas-t/Chocolat#68]
Compliments for your script, and thank you. It would be even more great if it had swipe support :)

**Comment by nicolas-t** [comment]
Hello,

thanks for the kind words.

I'd like to keep Chocolat as minimal and modular as possible, so I won't add a swipe features (which requires additional markup and logic).

But it can be added from the outside using hammer.js and the chocolat api:  
triggering `... .api().next()` when hammerjs detects a swipe tot he right 
triggering `... .api().prev()` when hammerjs detects a swipe tot he left 

It becomes more tricky if you want : 
 - to make the image move with the cursor/finger
 -  display the next/prev image, which have to be preloaded and have the same dimensions as the current/swiped one.

But it can be done, I don't have the time to do it from scratch but I can help you if you share your code.

Best,

**Comment by stratboy** [comment]
Ok thank you very much, have a nice day

Nicolas Turlais ha scritto:

**Comment by dastforush** [comment]
where can I find an example for dumb people like me?

**Comment by dastforush** [comment]
Would you please help me in this matter, I don't know how to select the chocolat-wrapper class name to get the hammer.js working.
https://codepen.io/anon/pen/OxvWMx
Than I'll be able to trigger the api.

**Comment by nicolas-t** [comment]
Yay !

Thank you for trying something !

i've made a demonstration on how to retrieve .chocolat-content (or .chocolat-wrapper) here : 
https://codepen.io/anon/pen/XeEMYa?editors=1010
I've made a gist as well because I hate codepen, I never now when it saves or not : 
https://gist.github.com/nicolas-t/a10a4278cf08f026fd0b294f51d6280c

The idea is to use the api to open chocolat, to wait for the opening animation to complete before accessing our elements and to bind hammer.

In fact you don't have to wait for the animation to complete, but it seems more elegant to me.

Don't hesitate if you have any question.

**Comment by dastforush** [comment]
Thank you for your help, I made another example this time with touchSwipe and it works properly on mobiles but on desktop it conflicts with zoomIn(e) the only solution I found was to change the click event on chocolat.js source to dblclick on zooming but it is unprofessional, I'll be appreciated if you could help me.

https://codepen.io/anon/pen/VMGrpg
